server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service-pro290
  cloud:
    gateway:
      routes:
        - id: user-api
          uri: http://localhost:5250
          predicates:
            - Path=/user/**
          #you can now hit this api gateway via: http://localhost:8888/user/abc

        - id: video-api
          uri: http://localhost:5287
          predicates:
            - Path=/video/**
